import { Routes } from '@angular/router';
import { PageSeo } from './shared/seo';

// GENERATED by scripts/import-articles.mjs from ../ghostwriter/wargr. Do not edit by hand.
export const routes: Routes = [
  {
    path: '',
    loadComponent: () => import('./pages/home.component').then((m) => m.HomeComponent),
    title: 'Wargr — essays by Michael Wargr',
    data: { seo: {"path":"/","description":"Essays by Michael Wargr on philosophy, ethics, fear, self-deception, conformity, purpose, pain, and human nature.","headline":"Essays by Michael Wargr","about":["Philosophy","Ethics","Human nature","Fear","Self-deception","Conformity","Purpose","Pain","Accountability","Moral psychology"],"itemList":[{"url":"https://wargr.com/mercy-of-death/","name":"The strange mercy of death"},{"url":"https://wargr.com/babylons-whore/","name":"The whore of Babylon was always us"},{"url":"https://wargr.com/knowing-yourself/","name":"The side effect of knowing yourself"},{"url":"https://wargr.com/slaughterhouse/","name":"How we choose the slaughterhouse"},{"url":"https://wargr.com/corruption/","name":"How fear turns the good in us into corruption"}]} satisfies PageSeo },
  },
  {
    path: 'mercy-of-death',
    loadComponent: () => import('./articles/mercy-of-death.component').then((m) => m.ArticleMercyOfDeathComponent),
    title: "The strange mercy of death — Michael Wargr",
    data: { seo: {"path":"/mercy-of-death/","description":"I was fifteen when death moved out of the distance and into the bed beside me, and it took years before I stopped seeing it as an enemy.","ogType":"article","headline":"The strange mercy of death","keywords":"The strange mercy of death essay, death essay, death, mortality, acceptance, cancer, philosophy, memoir, fear, peace, existential, life, illness, family, loss, contemplation, grief, Michael Wargr, Wargr essays, philosophy essays, essays on human nature","about":["The strange mercy of death essay","death essay","death","mortality","acceptance","cancer","philosophy","memoir","fear","peace","existential","life","illness","family","loss","contemplation","grief","Michael Wargr","Wargr essays","philosophy essays","essays on human nature"],"datePublished":"2026-07-09T12:00:00Z","dateModified":"2026-07-21T15:55:02+02:00","wordCount":2690,"readingTime":13,"imageAlt":"The strange mercy of death, an essay by Michael Wargr.","articleSection":"death","relatedSlugs":["knowing-yourself","babylons-whore","slaughterhouse"],"prevPath":"/babylons-whore/","ogImage":"https://wargr.com/assets/articles/mercy-of-death-og.jpg"} satisfies PageSeo },
  },
  {
    path: 'babylons-whore',
    loadComponent: () => import('./articles/babylons-whore.component').then((m) => m.ArticleBabylonsWhoreComponent),
    title: "The whore of Babylon was always us — Michael Wargr",
    data: { seo: {"path":"/babylons-whore/","description":"I thought religion was a trick for gullible people. Then the old stories started looking less like superstition and more like a report on the crowd, and on me.","ogType":"article","headline":"The whore of Babylon was always us","keywords":"The whore of Babylon was always us essay, religion essay, religion, whore of babylon, babylon, demons, conformity, belonging, human nature, psychology, groupthink, truth, belief, propaganda, authority, dissent, scepticism, revelation, crowd psychology, Michael Wargr, Wargr essays, philosophy essays, essays on human nature","about":["The whore of Babylon was always us essay","religion essay","religion","whore of babylon","babylon","demons","conformity","belonging","human nature","psychology","groupthink","truth","belief","propaganda","authority","dissent","scepticism","revelation","crowd psychology","Michael Wargr","Wargr essays","philosophy essays","essays on human nature"],"datePublished":"2026-07-09T12:00:00Z","dateModified":"2026-07-21T15:55:02+02:00","wordCount":1677,"readingTime":8,"imageAlt":"The whore of Babylon was always us, an essay by Michael Wargr.","articleSection":"religion","relatedSlugs":["slaughterhouse","knowing-yourself","mercy-of-death"],"prevPath":"/knowing-yourself/","nextPath":"/mercy-of-death/","ogImage":"https://wargr.com/assets/articles/babylons-whore-og.jpg"} satisfies PageSeo },
  },
  {
    path: 'knowing-yourself',
    loadComponent: () => import('./articles/knowing-yourself.component').then((m) => m.ArticleKnowingYourselfComponent),
    title: "The side effect of knowing yourself — Michael Wargr",
    data: { seo: {"path":"/knowing-yourself/","description":"The most confident people I have known never seem particularly interested in the question of how they look. That, it turns out, is the trick.","ogType":"article","headline":"The side effect of knowing yourself","keywords":"The side effect of knowing yourself essay, self-knowledge essay, self-knowledge, confidence, identity, self-image, authenticity, philosophy, psychology, projection, acceptance, human nature, ego, critique, freedom, observation, presence, Michael Wargr, Wargr essays, philosophy essays, essays on human nature","about":["The side effect of knowing yourself essay","self-knowledge essay","self-knowledge","confidence","identity","self-image","authenticity","philosophy","psychology","projection","acceptance","human nature","ego","critique","freedom","observation","presence","Michael Wargr","Wargr essays","philosophy essays","essays on human nature"],"datePublished":"2026-07-09T12:00:00Z","dateModified":"2026-07-12T19:56:17+02:00","wordCount":1014,"readingTime":5,"imageAlt":"The side effect of knowing yourself, an essay by Michael Wargr.","articleSection":"self-knowledge","relatedSlugs":["babylons-whore","mercy-of-death","corruption"],"prevPath":"/slaughterhouse/","nextPath":"/babylons-whore/","ogImage":"https://wargr.com/assets/articles/knowing-yourself-og.jpg"} satisfies PageSeo },
  },
  {
    path: 'slaughterhouse',
    loadComponent: () => import('./articles/slaughterhouse.component').then((m) => m.ArticleSlaughterhouseComponent),
    title: "Herd mentality and the slaughterhouse — Michael Wargr",
    data: { seo: {"path":"/slaughterhouse/","description":"An essay on herd mentality, conformity, propaganda, and the invisible ways people choose the stories that lead them.","ogType":"article","headline":"How we choose the slaughterhouse","keywords":"herd mentality, conformity, propaganda, mass psychology, consensus, dissent, media manipulation, groupthink, How we choose the slaughterhouse essay, philosophy essay, philosophy, herd, society, truth, courage, manipulation, media, narrative, awakening, human nature, Michael Wargr, Wargr essays, philosophy essays, essays on human nature","about":["herd mentality","conformity","propaganda","mass psychology","consensus","dissent","media manipulation","groupthink","How we choose the slaughterhouse essay","philosophy essay","philosophy","herd","society","truth","courage","manipulation","media","narrative","awakening","human nature","Michael Wargr","Wargr essays","philosophy essays","essays on human nature"],"datePublished":"2026-05-24T20:51:15+02:00","dateModified":"2026-07-12T19:56:17+02:00","wordCount":1093,"readingTime":5,"imageAlt":"Meat on a table in a slaughterhouse, matching an essay on conformity and herd mentality.","articleSection":"philosophy","relatedSlugs":["babylons-whore","corruption","knowing-yourself"],"prevPath":"/corruption/","nextPath":"/knowing-yourself/","ogImage":"https://wargr.com/assets/articles/slaughterhouse-og.jpg"} satisfies PageSeo },
  },
  {
    path: 'corruption',
    loadComponent: () => import('./articles/corruption.component').then((m) => m.ArticleCorruptionComponent),
    title: "How fear turns good people into corruption — Michael Wargr",
    data: { seo: {"path":"/corruption/","description":"An essay on corruption, moral compromise, fear, integrity, and how good people become what they once opposed.","ogType":"article","headline":"How fear turns the good in us into corruption","keywords":"how good people become corrupt, corruption, moral compromise, fear and integrity, ethical failure, power and responsibility, self-deception, character, How fear turns the good in us into corruption essay, ethics essay, ethics, integrity, business, power, philosophy, human nature, leadership, responsibility, identity, courage, morality, decision-making, Michael Wargr, Wargr essays, philosophy essays, essays on human nature","about":["how good people become corrupt","corruption","moral compromise","fear and integrity","ethical failure","power and responsibility","self-deception","character","How fear turns the good in us into corruption essay","ethics essay","ethics","integrity","business","power","philosophy","human nature","leadership","responsibility","identity","courage","morality","decision-making","Michael Wargr","Wargr essays","philosophy essays","essays on human nature"],"datePublished":"2026-05-23T16:18:02+02:00","dateModified":"2026-07-12T19:56:17+02:00","wordCount":776,"readingTime":4,"imageAlt":"A solitary figure in a dark room, matching an essay on fear, integrity, and corruption.","articleSection":"ethics","relatedSlugs":["knowing-yourself","slaughterhouse","babylons-whore"],"nextPath":"/slaughterhouse/","ogImage":"https://wargr.com/assets/articles/corruption-og.jpg"} satisfies PageSeo },
  },
  {
    path: '**',
    loadComponent: () => import('./pages/not-found.component').then((m) => m.NotFoundComponent),
    title: 'Not found — Wargr',
    data: { seo: { path: '/404', description: 'Not found.', noindex: true } satisfies PageSeo },
  },
];
