import { Routes } from '@angular/router';
import { PageSeo } from './shared/seo';

// GENERATED by scripts/import-articles.mjs from ../ghostwriter/wargr. Do not edit by hand.
export const routes: Routes = [
  {
    path: '',
    loadComponent: () => import('./pages/home.component').then((m) => m.HomeComponent),
    title: 'Wargr — essays by Michael Wargr',
    data: { seo: { path: '/', description: 'Essays by Michael Wargr.' } satisfies PageSeo },
  },
  {
    path: 'wtf-is-self-love',
    loadComponent: () => import('./articles/wtf-is-self-love.component').then((m) => m.ArticleWtfIsSelfLoveComponent),
    title: "WTF is self-love? — Wargr",
    data: { seo: { path: '/wtf-is-self-love/', description: "Most people are crueller to themselves than they would ever be to the rudest of strangers. They have been doing it so long they no longer hear it.", ogType: 'article', keywords: "self-love, loneliness, mental health, inner voice, self-talk, wellness-critique, philosophy, psychology, identity, kindness, discipline, acceptance, presence, contemplation, human nature" } satisfies PageSeo },
  },
  {
    path: 'whom-to-listen-to',
    loadComponent: () => import('./articles/whom-to-listen-to.component').then((m) => m.ArticleWhomToListenToComponent),
    title: "The one you should have listened to — Wargr",
    data: { seo: { path: '/whom-to-listen-to/', description: "When a hundred people agree about something and one person doesn't, the one person is usually wrong. Until they aren't, and the cost of having dismissed them has already been paid.", ogType: 'article', keywords: "philosophy, science, history, consensus, dissent, contrarian, truth, ideas, scepticism, expertise, institutions, paradigm shift, medical history, intellectual courage, mavericks" } satisfies PageSeo },
  },
  {
    path: 'stop-the-pain',
    loadComponent: () => import('./articles/stop-the-pain.component').then((m) => m.ArticleStopThePainComponent),
    title: "How to stop the pain — Wargr",
    data: { seo: { path: '/stop-the-pain/', description: "The pain you have been outrunning has not moved. It is exactly where you left it, waiting to be heard.", ogType: 'article', keywords: "pain, healing, addiction, escape, acceptance, submission, philosophy, mental health, suffering, self-help-critique, presence, stillness, avoidance, numbing, human nature" } satisfies PageSeo },
  },
  {
    path: 'stop-chasing-purpose',
    loadComponent: () => import('./articles/stop-chasing-purpose.component').then((m) => m.ArticleStopChasingPurposeComponent),
    title: "Stop chasing purpose — Wargr",
    data: { seo: { path: '/stop-chasing-purpose/', description: "The search for purpose is a trap most people walk into willingly. It ends only when they notice the search is the problem.", ogType: 'article', keywords: "philosophy, purpose, meaning, identity, acceptance, life, work, peace, human nature, existential, search, narrative, simplicity, contrarian, self-help-critique" } satisfies PageSeo },
  },
  {
    path: 'slaughterhouse',
    loadComponent: () => import('./articles/slaughterhouse.component').then((m) => m.ArticleSlaughterhouseComponent),
    title: "How we choose the slaughterhouse — Wargr",
    data: { seo: { path: '/slaughterhouse/', description: "You think you think for yourself. You don't. You follow, repeat, defend, and never notice the fence.", ogType: 'article', keywords: "philosophy, conformity, herd, society, propaganda, consensus, truth, courage, manipulation, mass psychology, dissent, media, narrative, awakening, human nature" } satisfies PageSeo },
  },
  {
    path: 'meant-well',
    loadComponent: () => import('./articles/meant-well.component').then((m) => m.ArticleMeantWellComponent),
    title: "I'm sorry. I meant well. — Wargr",
    data: { seo: { path: '/meant-well/', description: "The people who hurt you most rarely thought of themselves as the people hurting you.", ogType: 'article', keywords: "philosophy, ethics, accountability, intentions, outcomes, human nature, self-deception, moral philosophy, responsibility, relationships, politics, capitalism, socialism, psychology, contrarian" } satisfies PageSeo },
  },
  {
    path: 'corruption',
    loadComponent: () => import('./articles/corruption.component').then((m) => m.ArticleCorruptionComponent),
    title: "How fear turns the good in us into corruption — Wargr",
    data: { seo: { path: '/corruption/', description: "Corruption rarely starts with a bad person. It starts with a good one who has too much to lose.", ogType: 'article', keywords: "ethics, corruption, integrity, character, business, power, self-deception, philosophy, human nature, leadership, responsibility, identity, courage, morality, decision-making" } satisfies PageSeo },
  },
  {
    path: '**',
    loadComponent: () => import('./pages/not-found.component').then((m) => m.NotFoundComponent),
    title: 'Not found — Wargr',
    data: { seo: { path: '/404', description: 'Not found.', noindex: true } satisfies PageSeo },
  },
];
