import { Routes } from '@angular/router';
import { PageSeo } from './shared/seo';

// GENERATED by scripts/import-articles.mjs from ../ghostwriter/wargr. Do not edit by hand.
export const routes: Routes = [
  {
    path: '',
    loadComponent: () => import('./pages/home.component').then((m) => m.HomeComponent),
    title: 'Wargr — essays by Michael Wargr',
    data: { seo: {"path":"/","description":"Essays by Michael Wargr.","itemList":[{"url":"https://wargr.com/wtf-is-self-love/","name":"WTF is self-love?"},{"url":"https://wargr.com/whom-to-listen-to/","name":"The one you should have listened to"},{"url":"https://wargr.com/stop-the-pain/","name":"How to stop the pain"},{"url":"https://wargr.com/stop-chasing-purpose/","name":"Stop chasing purpose"},{"url":"https://wargr.com/slaughterhouse/","name":"How we choose the slaughterhouse"},{"url":"https://wargr.com/meant-well/","name":"I'm sorry. I meant well."},{"url":"https://wargr.com/corruption/","name":"How fear turns the good in us into corruption"}]} satisfies PageSeo },
  },
  {
    path: 'wtf-is-self-love',
    loadComponent: () => import('./articles/wtf-is-self-love.component').then((m) => m.ArticleWtfIsSelfLoveComponent),
    title: "WTF is self-love? — Wargr",
    data: { seo: {"path":"/wtf-is-self-love/","description":"Most people are crueller to themselves than they would ever be to the rudest of strangers. They have been doing it so long they no longer hear it.","ogType":"article","keywords":"self-love, loneliness, mental health, inner voice, self-talk, wellness-critique, philosophy, psychology, identity, kindness, discipline, acceptance, presence, contemplation, human nature","datePublished":"2026-06-06T03:07:42+02:00","wordCount":516,"readingTime":3,"articleSection":"self-love","relatedSlugs":["stop-the-pain","stop-chasing-purpose","corruption"],"prevPath":"/whom-to-listen-to/"} satisfies PageSeo },
  },
  {
    path: 'whom-to-listen-to',
    loadComponent: () => import('./articles/whom-to-listen-to.component').then((m) => m.ArticleWhomToListenToComponent),
    title: "The one you should have listened to — Wargr",
    data: { seo: {"path":"/whom-to-listen-to/","description":"When a hundred people agree about something and one person doesn't, the one person is usually wrong. Until they aren't, and the cost of having dismissed them has already been paid.","ogType":"article","keywords":"philosophy, science, history, consensus, dissent, contrarian, truth, ideas, scepticism, expertise, institutions, paradigm shift, medical history, intellectual courage, mavericks","datePublished":"2026-06-06T03:07:42+02:00","wordCount":941,"readingTime":5,"articleSection":"philosophy","relatedSlugs":["slaughterhouse","meant-well","stop-chasing-purpose"],"prevPath":"/stop-the-pain/","nextPath":"/wtf-is-self-love/"} satisfies PageSeo },
  },
  {
    path: 'stop-the-pain',
    loadComponent: () => import('./articles/stop-the-pain.component').then((m) => m.ArticleStopThePainComponent),
    title: "How to stop the pain — Wargr",
    data: { seo: {"path":"/stop-the-pain/","description":"The pain you have been outrunning has not moved. It is exactly where you left it, waiting to be heard.","ogType":"article","keywords":"pain, healing, addiction, escape, acceptance, submission, philosophy, mental health, suffering, self-help-critique, presence, stillness, avoidance, numbing, human nature","datePublished":"2026-06-06T03:07:42+02:00","wordCount":940,"readingTime":5,"articleSection":"pain","relatedSlugs":["wtf-is-self-love","stop-chasing-purpose","whom-to-listen-to"],"prevPath":"/stop-chasing-purpose/","nextPath":"/whom-to-listen-to/"} satisfies PageSeo },
  },
  {
    path: 'stop-chasing-purpose',
    loadComponent: () => import('./articles/stop-chasing-purpose.component').then((m) => m.ArticleStopChasingPurposeComponent),
    title: "Stop chasing purpose — Wargr",
    data: { seo: {"path":"/stop-chasing-purpose/","description":"The search for purpose is a trap most people walk into willingly. It ends only when they notice the search is the problem.","ogType":"article","keywords":"philosophy, purpose, meaning, identity, acceptance, life, work, peace, human nature, existential, search, narrative, simplicity, contrarian, self-help-critique","datePublished":"2026-06-06T03:07:42+02:00","wordCount":483,"readingTime":2,"articleSection":"philosophy","relatedSlugs":["stop-the-pain","wtf-is-self-love","corruption"],"prevPath":"/slaughterhouse/","nextPath":"/stop-the-pain/"} satisfies PageSeo },
  },
  {
    path: 'slaughterhouse',
    loadComponent: () => import('./articles/slaughterhouse.component').then((m) => m.ArticleSlaughterhouseComponent),
    title: "How we choose the slaughterhouse — Wargr",
    data: { seo: {"path":"/slaughterhouse/","description":"You think you think for yourself. You don't. You follow, repeat, defend, and never notice the fence.","ogType":"article","keywords":"philosophy, conformity, herd, society, propaganda, consensus, truth, courage, manipulation, mass psychology, dissent, media, narrative, awakening, human nature","datePublished":"2026-06-06T03:07:42+02:00","wordCount":1033,"readingTime":5,"articleSection":"philosophy","relatedSlugs":["whom-to-listen-to","corruption","stop-chasing-purpose"],"prevPath":"/meant-well/","nextPath":"/stop-chasing-purpose/"} satisfies PageSeo },
  },
  {
    path: 'meant-well',
    loadComponent: () => import('./articles/meant-well.component').then((m) => m.ArticleMeantWellComponent),
    title: "I'm sorry. I meant well. — Wargr",
    data: { seo: {"path":"/meant-well/","description":"The people who hurt you most rarely thought of themselves as the people hurting you.","ogType":"article","keywords":"philosophy, ethics, accountability, intentions, outcomes, human nature, self-deception, moral philosophy, responsibility, relationships, politics, capitalism, socialism, psychology, contrarian","datePublished":"2026-06-06T03:07:42+02:00","wordCount":1443,"readingTime":7,"articleSection":"philosophy","relatedSlugs":["corruption","stop-chasing-purpose","whom-to-listen-to"],"prevPath":"/corruption/","nextPath":"/slaughterhouse/"} satisfies PageSeo },
  },
  {
    path: 'corruption',
    loadComponent: () => import('./articles/corruption.component').then((m) => m.ArticleCorruptionComponent),
    title: "How fear turns the good in us into corruption — Wargr",
    data: { seo: {"path":"/corruption/","description":"Corruption rarely starts with a bad person. It starts with a good one who has too much to lose.","ogType":"article","keywords":"ethics, corruption, integrity, character, business, power, self-deception, philosophy, human nature, leadership, responsibility, identity, courage, morality, decision-making","datePublished":"2026-06-06T03:07:42+02:00","wordCount":660,"readingTime":3,"articleSection":"ethics","relatedSlugs":["meant-well","slaughterhouse","stop-chasing-purpose"],"nextPath":"/meant-well/","ogImage":"https://wargr.com/assets/articles/corruption-og.jpg"} satisfies PageSeo },
  },
  {
    path: '**',
    loadComponent: () => import('./pages/not-found.component').then((m) => m.NotFoundComponent),
    title: 'Not found — Wargr',
    data: { seo: { path: '/404', description: 'Not found.', noindex: true } satisfies PageSeo },
  },
];
